matthew-carroll/flutter_processing

CHANGELOG.md, pubspec.yaml
Changes to comply with pub.dev release rules
=> Changes to comply with pub.dev release rules

lib/src/_core.dart, test/core_test.dart, test/test_infra.dart
005: Simplified Sketch constructor to accept callbacks.
=> 005: Simplified Sketch constructor to accept callbacks.

README.md
Updated README with '2D Primitives' marked as completed
=> Updated README with '2D Primitives' marked as completed

CHANGELOG.md, pubspec.yaml
=> Published version 0.1.1

README.md, lib/src/_core.dart, test/random/random_test.dart
017: Implemented random() and randomSeed()
=> 017: Implemented random() and randomSeed()

README.md, example/lib/main.dart, example/macos/Podfile.lock, example/macos/Runner.xcodeproj/project.pbxproj, example/pubspec.lock, example/pubspec.yaml, lib/src/_core.dart
019: Implemented animation with frameRate and frameCount
=> 019: Implemented animation with frameRate and frameCount

example/lib/main.dart, example/lib/the_coding_train/coding_challenges/001_starfield.dart
021: Coding Challenge #001 - Starfield
=> 021: Coding Challenge #001 - Starfield

example/lib/main.dart, example/lib/the_coding_train/coding_challenges/004_purple-rain.dart
022: Coding Challenge #004 - Purple Rain
=> 022: Coding Challenge #004 - Purple Rain

lib/src/_core.dart
=> 025: Clipping

README.md, lib/src/_core.dart, test/input/keyboard_test.dart
=> 028: Keyboard input

example/lib/main.dart, lib/src/_core.dart
=> 029: Mouse input

lib/src/_core.dart
=> 030: Bitmap drawing

example/lib/main.dart, lib/src/_core.dart
=> get() and getRegion()

example/lib/main.dart, lib/src/_core.dart
033: loadPixels(), set(), updatePixels()
=> 033: loadPixels(), set(), updatePixels()

.run/001_ Starfield.run.xml, .run/004_ Purple Rain.run.xml, .run/052_ Random Walker.run.xml, example/lib/the_coding_train/coding_challenges/052_random_walker.dart, example/pubspec.lock, lib/src/_core.dart
034: Coding Challenge - Random Walker. Also added the missing behavior of drawing the previous frame at the beginning of the next frame.
=> 034: Coding Challenge - Random Walker

.run/006_ Mitosis Simulation.run.xml, example/lib/the_coding_train/coding_challenges/006_mitosis_simulation.dart
035: Coding Challenge - Mitosis Simulation
=> 035: Coding Challenge - Mitosis Simulation

example/lib/_processing_sketch_display.dart, example/lib/gif/gif.dart, example/lib/the_coding_train/coding_challenges/001_starfield.dart, example/lib/the_coding_train/coding_challenges/004_purple-rain.dart, example/lib/the_coding_train/coding_challenges/006_mitosis_simulation.dart, example/lib/the_coding_train/coding_challenges/052_random_walker.dart, example/macos/Podfile, example/macos/Podfile.lock, example/macos/Runner/DebugProfile.entitlements, example/pubspec.lock, example/pubspec.yaml, lib/src/_core.dart, pubspec.lock
Added gif recording to examples.
Also includes:
- new `ProcessingState` superclass for all demo `State` objects. It comes with hooks to save GIFs.
- regenerated Podfile to get rid of build warnings.
- adjusted `Processing` widget tree so that the Sketch overflows instead of shrinking when the window gets too small
=> Added gif recording to examples

lib/src/math/_calculations.dart
fixed broken map function
changed exp function to accept num instead of int and directly use math.exp
=> fix map function and change exp function

lib/src/_core.dart, lib/src/color/_setting.dart, lib/src/shape/_two_d_primitives.dart
052: Extract Color/Setting to mixin
=> 052: Extract Color/Setting to mixin

lib/src/_core.dart, lib/src/image/_loading_and_displaying.dart, lib/src/image/_pixels.dart, lib/src/output/_image.dart, lib/src/shape/_attributes.dart, lib/src/transform/_transform.dart
053: Extract mixins for Image/Loading & Saving, Image/Pixels, Shape/Attributes, Transform.
=> 053: Extract mixins for Image/Loading & Saving, Image/Pixels, Shape/Attributes, Transform.

CONTRIBUTING.md, README.md, pubspec.yaml
Create CONTRIBUTING and updated README
=> Create CONTRIBUTING and updated README

CONTRIBUTING.md
Updated CONTRIBUTING with examples and more info
=> Updated CONTRIBUTING with examples and more info

example/lib/app_screen.dart, example/lib/demos/_hacking_demo.dart, example/lib/demos/perlin_noise_demo.dart, example/lib/gif_maker.dart, example/lib/main.dart, example/lib/the_coding_train/coding_challenges/001_starfield.dart, example/lib/the_coding_train/coding_challenges/004_purple-rain.dart, example/lib/the_coding_train/coding_challenges/006_mitosis_simulation.dart, example/lib/the_coding_train/coding_challenges/028_metaballs.dart, example/lib/the_coding_train/coding_challenges/030_phyllotaxis.dart, example/lib/the_coding_train/coding_challenges/050_circle-packing-with-text.dart, example/lib/the_coding_train/coding_challenges/050_circle-packing.dart, example/lib/the_coding_train/coding_challenges/052_random_walker.dart, example/pubspec.lock, example/pubspec.yaml, pubspec.lock
056: Add drawer to example app
=> 056: Add drawer to example app

example/lib/_processing_sketch_display.dart, example/lib/app_screen.dart, example/lib/demos/_hacking_demo.dart, example/lib/demos/perlin_noise_demo.dart
057: Let the user select the background color
=> 057: Let the user select the background color

test/color/color_test.dart, test/constants/constants_test.dart, test/core/core_test.dart, test/environment/environment_test.dart, test/image/loading_and_displaying_test.dart, test/math/trigonometry_test.dart, test/random/random_test.dart, test/shape/attributes.dart, test/shape/two_d_primitives_test.dart, test/test_infra.dart, test/transform/transform_test.dart
058: Create custom spec test method
=> 058: Create custom spec test method

example/lib/main.dart, example/lib/the_coding_train/coding_challenges/124_boids.dart, lib/flutter_processing.dart, lib/src/math/_pvector.dart, lib/src/transform/_transform.dart, test/math/pvector_test.dart
Implemented PVector (Resolves #68)
=> Implemented PVector (Resolves #68)

example/lib/demos/_empty_sketch.dart, example/lib/demos/perlin_noise_demo.dart, example/lib/the_coding_train/coding_challenges/001_starfield.dart, example/lib/the_coding_train/coding_challenges/003_snake_game.dart, example/lib/the_coding_train/coding_challenges/004_purple-rain.dart, example/lib/the_coding_train/coding_challenges/006_mitosis_simulation.dart, example/lib/the_coding_train/coding_challenges/028_metaballs.dart, example/lib/the_coding_train/coding_challenges/030_phyllotaxis.dart, example/lib/the_coding_train/coding_challenges/031_flappy_bird.dart, example/lib/the_coding_train/coding_challenges/050_circle-packing-with-text.dart, example/lib/the_coding_train/coding_challenges/050_circle-packing.dart, example/lib/the_coding_train/coding_challenges/052_random_walker.dart, example/lib/the_coding_train/coding_challenges/085_game_of_life.dart, example/lib/the_coding_train/coding_challenges/124_boids.dart, lib/src/_sketch.dart, test/color/color_test.dart, test/color/setting_test.dart, test/complex_shapes_test.dart, test/constants/constants_test.dart, test/core/core_test.dart, test/decode_image_test.dart, test/environment/environment_test.dart, test/image/loading_and_displaying_test.dart, test/input/keyboard_test.dart, test/math/trigonometry_test.dart, test/random/random_test.dart, test/shape/attributes_test.dart, test/shape/two_d_primitives_test.dart, test/shape/vertex_test.dart, test/transform/transform_test.dart
Remove unnecessary awaits for setup() and draw()
=> Remove unnecessary awaits for setup() and draw()

example/lib/generative_art/network.dart, example/lib/generative_art/solar_storm.dart, example/lib/generative_art/wobbly_swarm.dart, example/lib/the_coding_train/coding_challenges/024_perlin_noise_flow_field.dart
Adjusted example app artwork colors and sizes
=> Adjusted example app artwork colors and sizes

CHANGELOG.md, pubspec.yaml
=> Release v0.2.0
